name:                project
version:             0.1.0.0
github:              "githubuser/project"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/project#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  http-server:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-types
    - pretty-simple
    - wai
    - warp
